### ISSUE TITLE
Leftover Blue on Threads updated

### ISSUE THREAD

**Issue by el-profesor926** [el-profesor926/OcUK-Theme-Xen-Minimal-Dark#2]
Looks like there is left over Blue on "Threads below this have not been updated since your last visit but have unread messages."

See screenshot.

![Capture](https://user-images.githubusercontent.com/5588454/106258186-6e579180-6215-11eb-97fb-b965dc6822d2.PNG)

**Comment by wiiija** [comment]
Need a link to the thread in question please mate

**Comment by el-profesor926** [comment]
It's not on a specific thread it's when you leave a page open for a while and it tells you that there's been posts.  It's easy enough to sort I'll do it tonight when I get in.

You can't see it until you leave the forum open for a while anyway.

**Comment by el-profesor926** [comment]
Couldn't find the Blue so waiting till I get new threads.  It popped up before now it won't popup automatically so just going to see if it comes back up then fix it.

**Comment by el-profesor926** [comment]
Found it! Correcting the code now.

![Capture](https://user-images.githubusercontent.com/5588454/106624467-99bbe280-656d-11eb-8574-cfcca8973ec2.PNG)

**Comment by el-profesor926** [comment]
Resolved in latest update v1.0.5
